### ISSUE TITLE
Consider dropping flutter dependency

### ISSUE THREAD

**Issue by jonasfj** [gskinnerTeam/flutter-universal-platform#1]
Just a friendly note, that if you don't use flutter and drop dependency on it, the this package will work for dart cli scripts and code generators too..

https://github.com/gskinnerTeam/flutter-universal-platform/blob/7de13c480b176fd6c83daf2e2c18ea27c82dba4a/pubspec.yaml#L11

**Comment by esDotDev** [comment]
Ahh, will do, thanks!
