### ISSUE TITLE
Force flutter to use universal platform

### ISSUE THREAD

**Issue by BerlinLion** [gskinnerTeam/flutter-universal-platform#12]
I have several issues with a lot of packages, running on the web-chrome, because of the error in the standard platform package. But this universal-platform package solves that issue. Is there a way to force flutter to use "universal-platform" instead of the standard implemented "platform" of flutter?!

**Comment by esDotDev** [comment]
I wish! They are aware of this issue, but not sure what the plans are to fix it.

**Comment by trailerzone** [comment]
might be able to create something where it overrides the internal function, i am kinda new to the language but i've seen some people do this with other areas involving the core
