### ISSUE TITLE
echart not working in web 

### ISSUE THREAD

**Issue by matheshwaran** [gskinnerTeam/flutter-universal-platform#22]
Hi , i want add san key chart to my project , am using echarts plugin which is working fine in Mobile, in Web its throwing below error

unsupported operation platform. _operating system flutter

plugin : https://pub.dev/packages/flutter_echarts

Is there any other way that i can use san key chart into flutter web 

need your support

**Comment by esDotDev** [comment]
Nope, they will need to modify their lib to not use `Platform`, you can fork their lib and do it yourself, or make an issue.
