### ISSUE TITLE
Kind of a bug: analysis_options includes pedantic but pubspec.yaml does not depend on padentic?

### ISSUE THREAD

**Issue by emme1444** [gskinnerTeam/flutter-universal-platform#5]
Upon locally cloning and inspecting the repository, I found that the `analysis_options.yaml` file depends on `pedantic`'s `analysis_options.yaml` however, there is no such dependency in the top-level `pubspec.yaml`.

My text editor (VSCode) gives me a warning about it not finding it. 

Is this absence intentional? Or maybe I'm stupid?

If not, I can make a PR real quick, if you could give me some pointers. If that's okay?

Thanks for the package anyhow!

**Comment by esDotDev** [comment]
Definitely not intentional, a PR would be great! Please remove pedantic
wherever it is referenced.

**Comment by emme1444** [comment]
Okay good! There you go.
